menu:
    Home: /
    Archive: /archives/
    About: "http://jeremys.life"

title: Jeremy's Blog
keywords: Jeremy,Jeremy Fan,Blog,博客,技术,前端,生活
description: Jeremy Fan's Blog，14 号院

favicon: /favicon.ico?v=2018

# Copyright Infomation
startyear: 2017