menu:
    Home: /
    Archive: /archives/
    About: "http://jeremyfan.name"

title: Jeremy's Blog
description: Jeremy Fan's Blog，14 号院

favicon: /favicon.ico?v=2018

# Copyright Infomation
startyear: 2017